Hotfix: config.py typo

diff --git a/.github/workflows/docker-build-deploy.yml b/.github/workflows/docker-build-deploy.yml
--- a/.github/workflows/docker-build-deploy.yml
+++ b/.github/workflows/docker-build-deploy.yml
@@ -40,8 +40,6 @@ jobs:
           name: telegram_bot_image
           path: telegram_bot_image.tar.gz
 
-<<<<<<< Updated upstream
-=======
       - name: copy files to target server via scp
         uses: appleboy/scp-action@v0.1.3
         with:
@@ -51,8 +49,6 @@ jobs:
           source: "./docker-compose.yml"
           target: "~/telegram_bot/"
 
-          
->>>>>>> Stashed changes
       - name: Deploy to Server via SSH
         uses: appleboy/ssh-action@v0.1.4
         with:
@@ -60,8 +56,16 @@ jobs:
           username: ${{ secrets.SERVER_USER }}
           key: ${{ secrets.SERVER_SSH_KEY }}
           script: |
-            cd ~/telegram_bot
-            gzip -d telegram_bot_image.tar.gz
-            docker load < telegram_bot_image.tar
-            docker-compose down
-            docker-compose up -d
+              set -e
+              cd ~/telegram_bot
+              docker-compose -f docker-compose.yml config > docker-compose.$(date +%Y%m%d_%H%M%S).yml
+              gzip -d telegram_bot_image.tar.gz
+              docker load < telegram_bot_image.tar
+              docker-compose down
+              if [ $? -ne 0 ]; then
+                  echo "Failed to stop containers" >&2
+                  exit 1
+              fi
+              docker-compose up -d
+              sleep 10
+              docker-compose ps --quiet | xargs docker inspect --format '{{.State.Health.Status}}' | grep -v healthy && exit 1
