Feature: Changed json files to Postgresql (#2)
* Feature: Changed json files to Postgresql

* 📝 Add docstrings to `dev` (#3)

Docstrings generation was requested by @CherryBrick.

* https://github.com/CherryBrick/yt-upload-tg-bot/pull/2#issuecomment-2599854167

The following files were modified:

* `handlers/admin_handlers.py`
* `handlers/default_handlers.py`
* `handlers/user_handlers.py`
* `main.py`
* `services/service_factory.py`
* `services/user_service.py`

Co-authored-by: coderabbitai[bot] <136622811+coderabbitai[bot]@users.noreply.github.com>

* Hotfix: config.py typo

---------

Co-authored-by: coderabbitai[bot] <136622811+coderabbitai[bot]@users.noreply.github.com>

diff --git a/.github/workflows/docker-build-deploy.yml b/.github/workflows/docker-build-deploy.yml
--- a/.github/workflows/docker-build-deploy.yml
+++ b/.github/workflows/docker-build-deploy.yml
@@ -14,7 +14,7 @@ jobs:
 
     steps:
       - name: Check out repository
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
 
       - name: Build Docker Image
         run: |
@@ -31,11 +31,23 @@ jobs:
     needs: build
 
     steps:
+      - name: Check out repository
+        uses: actions/checkout@v4
+
       - name: Download Docker Image
         uses: actions/download-artifact@v3
         with:
           name: telegram_bot_image
           path: telegram_bot_image.tar.gz
+
+      - name: copy files to target server via scp
+        uses: appleboy/scp-action@v0.1.3
+        with:
+          host: ${{ secrets.SERVER_HOST }}
+          username: ${{ secrets.SERVER_USER }}
+          key: ${{ secrets.SERVER_SSH_KEY }}
+          source: "./docker-compose.yml"
+          target: "~/telegram_bot/"
 
       - name: Deploy to Server via SSH
         uses: appleboy/ssh-action@master
@@ -44,7 +56,16 @@ jobs:
           username: ${{ secrets.SERVER_USER }}
           key: ${{ secrets.SERVER_SSH_KEY }}
           script: |
-            gzip -d telegram_bot_image.tar.gz
-            docker load < telegram_bot_image.tar
-            docker-compose down
-            docker-compose up -d
+              set -e
+              cd ~/telegram_bot
+              docker-compose -f docker-compose.yml config > docker-compose.$(date +%Y%m%d_%H%M%S).yml
+              gzip -d telegram_bot_image.tar.gz
+              docker load < telegram_bot_image.tar
+              docker-compose down
+              if [ $? -ne 0 ]; then
+                  echo "Failed to stop containers" >&2
+                  exit 1
+              fi
+              docker-compose up -d
+              sleep 10
+              docker-compose ps --quiet | xargs docker inspect --format '{{.State.Health.Status}}' | grep -v healthy && exit 1
