Fix: workflow, github actions'es verions, added missing image copy to server
Fix: workflow docker image copy to target server (#4)

Fix: deprecated versions of github actions (#5)

* Fix: workflow docker image copy to target server

* Fix: deprecated versions of github actions

Fix: workflow

Fix: workflow

diff --git a/.github/workflows/docker-build-deploy.yml b/.github/workflows/docker-build-deploy.yml
--- a/.github/workflows/docker-build-deploy.yml
+++ b/.github/workflows/docker-build-deploy.yml
@@ -20,8 +20,9 @@ jobs:
         run: |
           docker build -t $IMAGE_NAME .
           docker save $IMAGE_NAME | gzip > telegram_bot_image.tar.gz
+
       - name: Upload Docker Image as Artifact
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         with:
           name: telegram_bot_image
           path: telegram_bot_image.tar.gz
@@ -35,18 +36,32 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Download Docker Image
-        uses: actions/download-artifact@v3
+        uses: actions/download-artifact@v4
         with:
           name: telegram_bot_image
-          path: telegram_bot_image.tar.gz
-
+          path: ./
+      
+      - name: Verify files exist
+        run: |
+          ls -la
+          if [ ! -f docker-compose.yml ]; then
+            echo "docker-compose.yml not found!" >&2
+            exit 1
+          fi
+          if [ ! -f telegram_bot_image.tar.gz ]; then
+            echo "telegram_bot_image.tar.gz not found!" >&2
+            exit 1
+          fi
+      
       - name: copy files to target server via scp
-        uses: appleboy/scp-action@v0.1.3
+        uses: appleboy/scp-action@v0.1.7
         with:
           host: ${{ secrets.SERVER_HOST }}
           username: ${{ secrets.SERVER_USER }}
           key: ${{ secrets.SERVER_SSH_KEY }}
-          source: "./docker-compose.yml"
+          source: |
+            ${{ github.workspace }}/docker-compose.yml
+            ${{ github.workspace }}/telegram_bot_image.tar.gz
           target: "~/telegram_bot/"
 
       - name: Deploy to Server via SSH
